"""
Django settings for client project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv


import datetime
from datetime import timedelta
from pathlib import Path
from decouple import config, Csv
import dj_database_url
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# for production 
# DEBUG = True
# for development
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default=[], cast=Csv())

# Application definition

INSTALLED_APPS = [
    'jazzmin', #might use it in the future
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'drf_yasg',
    'django_celery_results',  # For storing task results in database
    'clientapp',
    'django.contrib.humanize',
    'quickbooks_integration',
    
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'client.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'clientapp' / 'templates',
            BASE_DIR / 'storefront_frontend' / 'pages',  # Frontend HTML pages
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'clientapp.views.notification_count_processor',  
            ],
        },
    },
]

WSGI_APPLICATION = 'client.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True

# Media files - responsible for uploads
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Static files - responsible for static files
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Static files directories
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'clientapp' / 'static',
]


STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'  # Disabled for development


# Login settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'login'

# QuickBooks Integration
load_dotenv()
QB_CLIENT_ID = os.getenv("QB_CLIENT_ID")
QB_CLIENT_SECRET = os.getenv("QB_CLIENT_SECRET")
QB_REDIRECT_URI = os.getenv("QB_REDIRECT_URI")
QB_ENVIRONMENT = os.getenv("QB_ENVIRONMENT", "sandbox")


# Messages framework (for success/error notifications)
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'error',
}

# DRF configuration (headless API defaults)- drf yasg
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
    "DEFAULT_FILTER_BACKENDS": (
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": "50/hour",
        "user": "500/hour",
    },
}

# JWT auth settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
CORS_ALLOW_CREDENTIALS = True

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

if not DEBUG:
    # For render
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True  
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # prevention of csrf errors
    CSRF_TRUSTED_ORIGINS = ['https://client2-o4ay.onrender.com'] 
else:
    #No HSTS forcing
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    
# Email settings - Using Mailgun SMTP (Render-compatible, free tier)
# Render-friendly alternative to SendGrid
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mailgun.org'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('MAILGUN_SMTP_LOGIN', default='')  # From Mailgun (format: postmaster@your-domain.mailgun.org)
EMAIL_HOST_PASSWORD = config('MAILGUN_SMTP_PASSWORD', default='')  # From Mailgun
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='PrintDuka <noreply@printduka.com>')

# Mailgun API Configuration (Optional - for advanced tracking features)
# Use this if you want to use Mailgun API instead of SMTP
# Get API key from: https://app.mailgun.com/app/account/security/api_keys
MAILGUN_API_KEY = config('MAILGUN_API_KEY', default='')  # API key from Mailgun (format: key-abc123...)
MAILGUN_DOMAIN = config('MAILGUN_DOMAIN', default='')  # Your sandbox domain (format: sandboxabc123...mailgun.org)
# Celery Configuration - Using Database-Backed Broker (No Redis needed!)
# Tasks are stored in database, processed by worker
# Results stored in database via django-celery-results
if not DEBUG:
    # Production: Use database broker (convert PostgreSQL URL to SQLAlchemy format)
    database_url = config('DATABASE_URL', default='')
    if database_url:
        # Convert postgresql://user:pass@host/db to sqla+postgresql://user:pass@host/db
        celery_broker_url = database_url.replace('postgres://', 'sqla+postgresql://').replace('postgresql://', 'sqla+postgresql://')
        CELERY_BROKER_URL = celery_broker_url
        CELERY_RESULT_BACKEND = celery_broker_url.replace('sqla+postgresql', 'db+postgresql')
    else:
        # Fallback if DATABASE_URL not set
        CELERY_BROKER_URL = 'memory://'
        CELERY_RESULT_BACKEND = 'cache+memory://'
else:
    # Local development: Use memory broker (simpler setup, no DB needed)
    CELERY_BROKER_URL = 'memory://'
    CELERY_RESULT_BACKEND = 'cache+memory://'

CELERY_BROKER_USE_SSL = False
CELERY_BROKER_POOL_LIMIT = 1
CELERY_BROKER_CONNECTION_RETRY = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes hard time limit
CELERY_RESULT_EXPIRES = 3600  # Results expire after 1 hour




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==================== JAZZMIN ADMIN CUSTOMIZATION ====================

#Jazzmin admin customization- Maybe for future use
JAZZMIN_SETTINGS = {
    "site_title": "PrintDuka Admin",
    "site_header": "PrintDuka",
    "site_brand": "PrintDuka Management System",
    "welcome_sign": "Welcome to PrintDuka Admin Portal",
    "copyright": "PrintDuka Ltd @ 2025",
    "search_model": ["clientapp.Client", "clientapp.Lead", "clientapp.Quote", "clientapp.Product"],
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "/", "new_window": True},
        {"model": "auth.User"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "clientapp.Client": "fas fa-user-tie",
        "clientapp.Lead": "fas fa-user-plus",
        "clientapp.Quote": "fas fa-file-invoice-dollar",
        "clientapp.LPO": "fas fa-file-invoice",
        "clientapp.Job": "fas fa-briefcase",
        "clientapp.Product": "fas fa-box",
        "clientapp.ProductTemplate": "fas fa-file-image",
        "clientapp.ProductCategory": "fas fa-folder",
        "clientapp.Vendor": "fas fa-truck",
        "clientapp.ActivityLog": "fas fa-history",
        "clientapp.Notification": "fas fa-bell",
    },
    "custom_css": "admin/css/dashboard_theme.css",
    
    # Theme colors
    "theme": {
        "primary": "#667eea",
        "secondary": "#34495e",
        "accent": "#764ba2",
        "dark": "#2c3e50",
        "light": "#ecf0f1",
        "info": "#3498db",
        "warning": "#f39c12",
        "danger": "#e74c3c",
        "success": "#27ae60",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,

}

JAZZMIN_UI_TWEAKS = {
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
}


# ============================================================================
# STOREFRONT CONFIGURATION
# ============================================================================

# Company Information
COMPANY_NAME = config('COMPANY_NAME', default='PrintDuka')
COMPANY_EMAIL = config('COMPANY_EMAIL', default='sales@printduka.com')
COMPANY_PHONE = config('COMPANY_PHONE', default='+254-700-000-000')
SALES_TEAM_EMAIL = config('SALES_TEAM_EMAIL', default='sales@printduka.com')

# Storefront URL
STOREFRONT_URL = config('STOREFRONT_URL', default='http://localhost:3000')

# Messaging Configuration (Africastalking for SMS/WhatsApp)
AFRICASTALKING_API_KEY = config('AFRICASTALKING_API_KEY', default='')
AFRICASTALKING_USERNAME = config('AFRICASTALKING_USERNAME', default='')

# Tax Configuration
TAX_RATE_KE = config('TAX_RATE_KE', default='18.00')  # Kenya VAT
TAX_RATE_UG = config('TAX_RATE_UG', default='18.00')  # Uganda VAT
TAX_RATE_TZ = config('TAX_RATE_TZ', default='18.00')  # Tanzania VAT
TAX_RATE_RW = config('TAX_RATE_RW', default='18.00')  # Rwanda VAT
TAX_RATE_ZA = config('TAX_RATE_ZA', default='15.00')  # South Africa VAT
TAX_RATE_US = config('TAX_RATE_US', default='0.00')   # US (varies by state)

# Turnaround Times (in days)
TURNAROUND_STANDARD_DAYS = config('TURNAROUND_STANDARD_DAYS', default=7, cast=int)
TURNAROUND_RUSH_DAYS = config('TURNAROUND_RUSH_DAYS', default=3, cast=int)
TURNAROUND_EXPEDITED_DAYS = config('TURNAROUND_EXPEDITED_DAYS', default=1, cast=int)

# Estimate Quote Settings
ESTIMATE_EXPIRY_DAYS = config('ESTIMATE_EXPIRY_DAYS', default=7, cast=int)
EMAIL_VERIFICATION_EXPIRY_HOURS = config('EMAIL_VERIFICATION_EXPIRY_HOURS', default=24, cast=int)
OTP_EXPIRY_MINUTES = config('OTP_EXPIRY_MINUTES', default=10, cast=int)

# Cache Configuration for OTP/Tokens
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'storefront-cache',
    }
}

# Logging Configuration
# Create logs directory if it doesn't exist
import os as _os
_logs_dir = BASE_DIR / 'logs'
if not _os.path.exists(_logs_dir):
    _os.makedirs(_logs_dir, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': str(BASE_DIR / 'logs' / 'storefront.log'),
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'clientapp.storefront_services': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'clientapp.storefront_views': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

