# Generated by Django 5.2.7 on 2025-11-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_of_measure_custom',
            field=models.CharField(blank=True, help_text="Custom unit if 'Other' is selected", max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_category',
            field=models.CharField(blank=True, default='Default', help_text='e.g., Print Products, Signage, Apparel', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_family',
            field=models.CharField(blank=True, default='Default', help_text='e.g., Business Cards Family', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, help_text='e.g., Business Cards, Flyers, Brochures', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('pieces', 'Pieces'), ('packs', 'Packs'), ('sets', 'Sets'), ('sqm', 'm²'), ('other', 'Other')], default='pieces', max_length=20),
        ),
    ]
