# Generated by Django 5.2.7 on 2025-11-03 06:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_job_jobattachment_jobproduct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='include_vat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_terms',
            field=models.CharField(choices=[('Prepaid', 'Prepaid Before Production'), ('Net 7', 'Net 7 Days'), ('Net 15', 'Net 15 Days'), ('Net 30', 'Net 30 Days'), ('Net 60', 'Net 60 Days')], default='Prepaid', max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='clientapp.client'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_id',
            field=models.CharField(db_index=True, editable=False, max_length=20),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['quote_id'], name='clientapp_q_quote_i_1c76ed_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status'], name='clientapp_q_status_54afbc_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['client'], name='clientapp_q_client__3e64e9_idx'),
        ),
    ]
