# Generated by Django 5.2.7 on 2025-11-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_product_unit_of_measure_custom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='auto_generate_code',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='internal_code',
            field=models.CharField(blank=True, help_text='Internal SKU/Code (auto-generated)', max_length=50, unique=True),
        ),
    ]
