# Generated by Django 5.2.7 on 2025-11-25 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0003_alter_product_auto_generate_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricing',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, default=15, help_text='Lowest possible vendor cost per piece (EVP)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='default_margin',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='minimum_margin',
            field=models.DecimalField(decimal_places=2, default=15, help_text='Below this triggers approval', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
