# Generated by Django 5.2.7 on 2025-11-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0003_quote_include_vat_quote_payment_terms_quote_terms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='cost_price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='markup_percentage',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='selling_price',
        ),
    ]
