# Generated by Django 5.2.7 on 2025-11-07 08:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0004_rename_cost_price_quote_unit_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('non_custom', 'Non-Custom'), ('semi_custom', 'Semi-Custom'), ('custom', 'Custom')], default='non_custom', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('availability', models.CharField(choices=[('always', 'Always Available'), ('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('lead_time', 'Lead Time')], default='always', max_length=20)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('lead_time', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('quote', 'Quote'), ('job', 'Job')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Costing'), ('in_progress', 'Costing In Progress'), ('costed', 'Costed'), ('sent_to_client', 'Sent To Client'), ('on_hold', 'On Hold'), ('in_production', 'In Production'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='costed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_costed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='production_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='production_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='production_status',
            field=models.CharField(choices=[('pending', 'Pending Costing'), ('in_progress', 'Costing In Progress'), ('costed', 'Costed'), ('sent_to_client', 'Sent To Client'), ('on_hold', 'On Hold'), ('in_production', 'In Production'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['production_status'], name='clientapp_q_product_414cf1_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionupdate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_updates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionupdate',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_updates', to='clientapp.job'),
        ),
        migrations.AddField(
            model_name='productionupdate',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_updates', to='clientapp.quote'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='clientapp_n_recipie_ad17f4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='clientapp_p_sku_523183_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='clientapp_p_product_854003_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['availability'], name='clientapp_p_availab_591d98_idx'),
        ),
        migrations.AddIndex(
            model_name='productionupdate',
            index=models.Index(fields=['update_type'], name='clientapp_p_update__f31545_idx'),
        ),
        migrations.AddIndex(
            model_name='productionupdate',
            index=models.Index(fields=['status'], name='clientapp_p_status_d20b40_idx'),
        ),
    ]
