# Generated by Django 5.2.7 on 2025-11-25 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0004_alter_productpricing_base_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricing',
            name='primary_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_products', to='clientapp.vendor'),
        ),
    ]
