# Generated by Django 5.2.7 on 2025-11-26 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0005_alter_productpricing_primary_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock Alert'), ('urgent_order', 'Urgent Order'), ('payment_due', 'Payment Due'), ('system_error', 'System Error'), ('new_lead', 'New Lead'), ('quote_expired', 'Quote Expired'), ('info', 'General Information')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='URL to related object', max_length=200)),
                ('visible_to_admins', models.BooleanField(default=True)),
                ('visible_to_production', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_created', to=settings.AUTH_USER_MODEL)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_alerts', to=settings.AUTH_USER_MODEL)),
                ('related_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.client')),
                ('related_lpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.lpo')),
                ('related_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.quote')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'is_dismissed'], name='clientapp_s_is_acti_6a926d_idx'), models.Index(fields=['severity'], name='clientapp_s_severit_3c189c_idx')],
            },
        ),
    ]
