# Generated by Django 5.2.7 on 2025-11-10 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0006_alter_lead_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('business_cards', 'Business Cards'), ('brochures', 'Brochures & Flyers'), ('posters', 'Posters & Banners'), ('t-shirts', 'T-Shirts & Apparel'), ('mugs', 'Mugs & Drinkware'), ('bags', 'Bags & Totes'), ('stickers', 'Stickers & Labels'), ('signage', 'Signage & Displays'), ('packaging', 'Packaging'), ('other', 'Other')], default='other', help_text='Product category for organization', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('B2B', 'B2B Company'), ('B2C', 'B2C Retail')], default='B2B', max_length=10),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='clientapp_p_categor_802c1e_idx'),
        ),
    ]
