# Generated by Django 5.2.7 on 2025-11-28 09:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0007_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['-vps_score_value', 'name']},
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='vendor',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vps_score',
            field=models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Good'), ('C', 'C - Acceptable')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vps_score_value',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='QCInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('delivered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('warehouse_location', models.CharField(default='Shelf A-15', max_length=50)),
                ('inspected_quantity', models.IntegerField()),
                ('print_quality_score', models.IntegerField(blank=True, null=True)),
                ('color_accuracy_score', models.IntegerField(blank=True, null=True)),
                ('material_quality_score', models.IntegerField(blank=True, null=True)),
                ('finishing_quality_score', models.IntegerField(blank=True, null=True)),
                ('overall_quality_score', models.IntegerField(blank=True, null=True)),
                ('print_quality_notes', models.TextField(blank=True)),
                ('color_accuracy_notes', models.TextField(blank=True)),
                ('material_quality_notes', models.TextField(blank=True)),
                ('finishing_quality_notes', models.TextField(blank=True)),
                ('overall_quality_notes', models.TextField(blank=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('notes_to_am', models.TextField(blank=True, help_text='Notes to Account Manager')),
                ('decision', models.CharField(blank=True, choices=[('pass', 'Pass - Approve for Delivery'), ('conditions', 'Pass with Conditions'), ('fail', 'Fail - Reject & Request Rework')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_inspections', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_inspections', to='clientapp.job')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_inspections', to='clientapp.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QCPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='qc_photos/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='clientapp.qcinspection')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vendors', models.ManyToManyField(related_name='specialties', to='clientapp.vendor')),
            ],
            options={
                'verbose_name_plural': 'Vendor Specialties',
            },
        ),
        migrations.CreateModel(
            name='VendorQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_time', models.IntegerField(help_text='Lead time in days')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selected', models.BooleanField(default=False)),
                ('notice', models.CharField(blank=True, help_text='e.g., Watch out (2 close misses this month)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_quotes', to='clientapp.job')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='clientapp.vendor')),
            ],
            options={
                'ordering': ['lead_time', 'total_cost'],
                'unique_together': {('job', 'vendor')},
            },
        ),
    ]
