# Generated by Django 5.2.7 on 2025-11-11 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0007_alter_product_options_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='clientapp.quote'),
        ),
    ]
