# Generated by Django 5.2.7 on 2025-12-01 08:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0008_alter_vendor_options_rename_is_active_vendor_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('process_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('outsourced', 'Outsourced'), ('in_house', 'In-house')], max_length=20)),
                ('standard_lead_time', models.IntegerField(help_text='Days')),
                ('pricing_type', models.CharField(choices=[('tier', 'Tier-Based Pricing'), ('formula', 'Formula-Based Pricing')], max_length=20)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_type', models.CharField(default='auto_approve', max_length=50)),
                ('approval_margin_threshold', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=100)),
                ('variable_type', models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('dropdown', 'Dropdown'), ('boolean', 'Boolean')], max_length=20)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='clientapp.process')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_id', models.CharField(max_length=50)),
                ('vps_score', models.DecimalField(decimal_places=2, help_text='Vendor Performance Score', max_digits=5)),
                ('priority', models.CharField(choices=[('preferred', 'Preferred'), ('alternative', 'Alternative'), ('backup', 'Backup')], default='alternative', max_length=20)),
                ('tier_costs', models.JSONField(blank=True, null=True)),
                ('formula_rates', models.JSONField(blank=True, null=True)),
                ('rush_enabled', models.BooleanField(default=False)),
                ('rush_fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rush_threshold_days', models.IntegerField(default=3)),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('standard_lead_time', models.IntegerField(help_text='Days')),
                ('rush_lead_time', models.IntegerField(blank=True, help_text='Days', null=True)),
                ('notes', models.TextField(blank=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_vendors', to='clientapp.process')),
            ],
            options={
                'ordering': ['priority', '-vps_score'],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_number', models.IntegerField()),
                ('quantity_from', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_to', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='clientapp.process')),
            ],
            options={
                'ordering': ['tier_number'],
                'unique_together': {('process', 'tier_number')},
            },
        ),
        migrations.CreateModel(
            name='ProcessTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_number', models.IntegerField()),
                ('quantity_from', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_to', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('margin_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('margin_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='clientapp.process')),
            ],
            options={
                'ordering': ['tier_number'],
                'unique_together': {('process', 'tier_number')},
            },
        ),
        migrations.CreateModel(
            name='VendorTierPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_number', models.IntegerField()),
                ('quantity_from', models.IntegerField()),
                ('quantity_to', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('process_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_pricing', to='clientapp.processvendor')),
            ],
            options={
                'ordering': ['tier_number'],
                'unique_together': {('process_vendor', 'tier_number')},
            },
        ),
    ]
