# Generated by Django 5.2.7 on 2025-11-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0008_job_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('B2B', 'B2B Business'), ('B2C', 'B2C Retail')], default='B2B', max_length=10),
        ),
    ]
