# Generated by Django 5.2.7 on 2025-12-02 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0009_process_processvariable_processvendor_pricingtier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lead_created', 'New Lead Created'), ('quote_reminder', 'Quote Creation Reminder'), ('quote_approved', 'Quote Approved by Client'), ('quote_sent_pt', 'Quote Sent to PT for Approval'), ('convert_lead', 'Convert Lead to Client'), ('delivery_ready', 'Delivery Ready for AM'), ('job_completed', 'Job Completed'), ('general', 'General Notification')], default='general', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='related_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.job'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.lead'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_quote_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='clientapp_n_created_3ad94e_idx'),
        ),
    ]
