# Generated by Django 5.2.7 on 2025-12-04 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0010_notification_action_label_notification_action_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricing',
            name='process',
            field=models.ForeignKey(blank=True, help_text='Select the costing process for this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='clientapp.process'),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='use_process_costs',
            field=models.BooleanField(default=True, help_text='Use costs from linked process, or override with custom values'),
        ),
        migrations.AddField(
            model_name='productvariable',
            name='source_process_variable',
            field=models.ForeignKey(blank=True, help_text='Source variable from process (if auto-imported)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variables', to='clientapp.processvariable'),
        ),
    ]
