# Generated by Django 5.2.7 on 2025-12-04 09:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0011_productpricing_process_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qcinspection',
            name='box_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='delivery_checklist',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='packaging_verified',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='shelf_location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='color_accuracy_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='finishing_quality_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='material_quality_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='notes_to_am',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='overall_quality_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='print_quality_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='reference_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('staged', 'Staged - Awaiting Pickup'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed')], default='staged', max_length=20)),
                ('staging_location', models.CharField(choices=[('shelf-a', 'Shelf A - Urgent/Priority'), ('shelf-b', 'Shelf B - Standard/Ready Today'), ('shelf-c', 'Shelf C - Future Delivery'), ('warehouse', 'Warehouse - Overflow')], default='shelf-b', max_length=20)),
                ('packaging_verified', models.JSONField(blank=True, default=dict)),
                ('package_photos', models.JSONField(blank=True, default=list)),
                ('notes_to_am', models.TextField(blank=True)),
                ('locked_evp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('handoff_confirmed', models.BooleanField(default=False)),
                ('handoff_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notify_am', models.BooleanField(default=True)),
                ('notify_via_email', models.BooleanField(default=True)),
                ('mark_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_created', to=settings.AUTH_USER_MODEL)),
                ('handoff_confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_confirmed', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='clientapp.job')),
                ('qc_inspection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='clientapp.qcinspection')),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='QCPhoto',
        ),
    ]
