# Generated by Django 5.2.7 on 2025-12-05 08:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0013_jobnote_jobvendorstage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['product', 'display_order']},
        ),
        migrations.AddField(
            model_name='productimage',
            name='associated_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientapp.productvariableoption'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='associated_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientapp.productvariable'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('product-photo', 'Product Photo'), ('detail', 'Detail/Close-up'), ('mockup', 'Mockup/In-Use'), ('size-comparison', 'Size Comparison'), ('sample', 'Sample/Example')], default='product-photo', max_length=30),
        ),
        migrations.AddField(
            model_name='productimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(help_text='For SEO & accessibility', max_length=255),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/images/%Y/%m/'),
        ),
    ]
