# Generated by Django 5.2.7 on 2025-12-05 08:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0014_alter_productimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_number',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='package_photos',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='qc_inspection',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='box_count',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='color_accuracy_notes',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='color_accuracy_score',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='delivered_date',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='delivery_checklist',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='delivery_notes',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='finishing_quality_notes',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='finishing_quality_score',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='inspected_quantity',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='material_quality_notes',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='material_quality_score',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='notes_to_am',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='overall_quality_notes',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='overall_quality_score',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='packaging_verified',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='print_quality_notes',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='print_quality_score',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='shelf_location',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='qcinspection',
            name='warehouse_location',
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='color_accuracy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='cutting_accuracy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='finishing_quality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='inspection_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='packaging_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='print_quality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='quantity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qcinspection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='actual_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='handoff_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoffs_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='locked_evp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='staging_location',
            field=models.CharField(choices=[('shelf-a', 'Shelf A'), ('shelf-b', 'Shelf B'), ('shelf-c', 'Shelf C'), ('counter', 'Counter'), ('warehouse', 'Warehouse')], default='shelf-b', max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('staged', 'Staged for Pickup'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='inspector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qcinspection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('rework', 'Needs Rework')], default='pending', max_length=20),
        ),
    ]
