# Generated by Django 5.2.7 on 2025-12-05 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0015_remove_delivery_delivery_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcinspection',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qc_inspections', to='clientapp.vendor'),
        ),
    ]
