# Generated by Django 5.2.7 on 2025-12-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0016_qcinspection_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Default delivery address'),
        ),
        migrations.AddField(
            model_name='client',
            name='delivery_instructions',
            field=models.TextField(blank=True, help_text='Specific delivery instructions (e.g., gate codes, contact person)'),
        ),
    ]
