# Generated by Django 5.2.7 on 2025-12-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0017_client_delivery_address_client_delivery_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
