# Generated by Django 5.2.8 on 2025-12-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0018_alter_client_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='internal_notes_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='lead_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='minimum_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Bank Transfer', 'Bank Transfer'), ('Mobile Money', 'Mobile Money'), ('Cash', 'Cash'), ('Check', 'Check')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('Net 7', 'Net 7 Days'), ('Net 14', 'Net 14 Days'), ('Net 30', 'Net 30 Days'), ('Prepaid', 'Prepaid'), ('Cash on Delivery', 'Cash on Delivery')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='quality_rating',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Fair', 'Fair')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='reliability_rating',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Fair', 'Fair')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='rush_capable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='specialization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tax_pin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
