# Generated by Django 5.2.7 on 2025-12-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0020_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
