# Generated by Django 5.2.7 on 2025-12-17 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0021_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customization_level',
            field=models.CharField(choices=[('non_customizable', 'Non-Customizable'), ('semi_customizable', 'Semi-Customizable'), ('fully_customizable', 'Fully Customizable')], default='non_customizable', help_text='Determines which pricing methods are available', max_length=30),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='formula_process',
            field=models.ForeignKey(blank=True, help_text='Formula-based pricing process for customizations', limit_choices_to={'pricing_type': 'formula', 'status': 'active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_using_formula', to='clientapp.process'),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='tier_process',
            field=models.ForeignKey(blank=True, help_text='Tier-based pricing process for quantity discounts', limit_choices_to={'pricing_type': 'tier', 'status': 'active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_using_tiers', to='clientapp.process'),
        ),
        migrations.CreateModel(
            name='ProcessVariableRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.DecimalField(decimal_places=2, help_text='Minimum value for this range', max_digits=10)),
                ('max_value', models.DecimalField(decimal_places=2, help_text='Maximum value for this range', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Base price for this range (KES)', max_digits=10)),
                ('rate', models.DecimalField(decimal_places=4, default=1.0, help_text='Multiplier rate for this range', max_digits=10)),
                ('order', models.IntegerField(default=0)),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='clientapp.processvariable')),
            ],
            options={
                'verbose_name': 'Variable Range',
                'verbose_name_plural': 'Variable Ranges',
                'ordering': ['order', 'min_value'],
            },
        ),
    ]
