# Generated by Django 5.2.8 on 2025-12-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0022_product_customization_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpricing',
            name='formula_process',
        ),
        migrations.RemoveField(
            model_name='productpricing',
            name='tier_process',
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price for non-customizable products', max_digits=12, null=True),
        ),
    ]
