# Generated by Django 5.2.7 on 2025-12-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0023_add_base_price_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base cost for formula-based pricing', max_digits=10),
        ),
        migrations.AddField(
            model_name='processvariable',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for this variable value (KES)', max_digits=10),
        ),
        migrations.AddField(
            model_name='processvariable',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Multiplier rate for this variable', max_digits=10),
        ),
        migrations.AddField(
            model_name='processvariable',
            name='variable_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Single value for this variable (e.g., 50, 1)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='processvariable',
            name='unit',
            field=models.CharField(blank=True, help_text='e.g., stitches, m, cm', max_length=50),
        ),
        migrations.AlterField(
            model_name='processvariable',
            name='variable_type',
            field=models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('dropdown', 'Dropdown'), ('boolean', 'Boolean')], default='number', max_length=20),
        ),
    ]
