# Generated by Django 5.2.7 on 2025-12-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0024_process_base_cost_processvariable_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processvariable',
            name='variable_type',
            field=models.CharField(choices=[('number', 'Number'), ('alphanumeric', 'Alphanumeric')], default='number', max_length=20),
        ),
        migrations.AlterField(
            model_name='processvariable',
            name='variable_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Single value for this variable (only for number type)', max_digits=10, null=True),
        ),
    ]
