# Generated by Django 5.2.8 on 2025-12-20 16:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0025_alter_processvariable_variable_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricing',
            name='formula_process',
            field=models.ForeignKey(blank=True, help_text='Formula-based pricing process (customization pricing)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formula_products', to='clientapp.process'),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='return_margin',
            field=models.DecimalField(decimal_places=2, default=30, help_text='Margin percentage for this product', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='tier_process',
            field=models.ForeignKey(blank=True, help_text='Tier-based pricing process (quantity discounts)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tier_products', to='clientapp.process'),
        ),
    ]
