# Generated by Django 5.2.8 on 2025-12-20 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0026_productpricing_formula_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='clientapp.product'),
        ),
    ]
