# Generated by Django 5.2.8 on 2025-12-21 11:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0027_quote_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Sent to PT', 'Sent to PT'), ('Costed', 'Costed'), ('Sent to Customer', 'Sent to Customer'), ('Approved', 'Approved'), ('Lost', 'Lost')], default='Draft', max_length=20),
        ),
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('customization_level_snapshot', models.CharField(max_length=30)),
                ('base_price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('variable_amount', models.DecimalField(decimal_places=2, default=0, help_text='Additional cost from variables', max_digits=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_line_items', to='clientapp.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='clientapp.quote')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['quote'], name='clientapp_q_quote_i_347984_idx')],
            },
        ),
    ]
