# Generated by Django 5.2.8 on 2026-01-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0028_add_quote_line_item_and_pricing_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='adjustment_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final adjustment (+/-)', max_digits=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='adjustment_reason',
            field=models.CharField(blank=True, help_text='Reason for adjustment', max_length=255),
        ),
        migrations.AddField(
            model_name='quote',
            name='custom_terms',
            field=models.TextField(blank=True, help_text='Custom terms & conditions for this quote'),
        ),
        migrations.AddField(
            model_name='quote',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Client PO/LPO reference', max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='shipping_charges',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Delivery/shipping cost', max_digits=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=16, help_text='Tax percentage (default 16% VAT)', max_digits=5),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount value', max_digits=12),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='percent', help_text='Discount type', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lead_created', 'New Lead Created'), ('quote_reminder', 'Quote Creation Reminder'), ('quote_approved', 'Quote Approved by Client'), ('quote_sent_pt', 'Quote Sent to PT for Approval'), ('quote_pt_approved', 'Quote Costed by PT'), ('quote_discount_request', 'Price Reduction Requested'), ('quote_adjustment_request', 'Quote Adjustments Requested'), ('convert_lead', 'Convert Lead to Client'), ('delivery_ready', 'Delivery Ready for AM'), ('job_completed', 'Job Completed'), ('general', 'General Notification')], max_length=50),
        ),
    ]
