# Generated by Django 5.2.7 on 2026-01-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0030_quote_discount_total_quote_subtotal_quote_tax_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('portal', 'Internal Portal'), ('ecommerce', 'Ecommerce'), ('api', 'API Integration')], default='portal', max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='channel',
            field=models.CharField(choices=[('portal', 'Internal Portal'), ('ecommerce', 'Ecommerce'), ('api', 'API Integration')], db_index=True, default='portal', max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='checkout_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('cart', 'Cart'), ('submitted', 'Submitted'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='Notes provided by customer (ecommerce/API)'),
        ),
    ]
