# Generated by Django 5.2.7 on 2026-01-08 13:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fix_person_in_charge_data(apps, schema_editor):
    """
    Set person_in_charge to a string ID ('1') so it satisfies the NOT NULL 
    constraint and can be cast to an integer during the AlterField step.
    """
    Job = apps.get_model('clientapp', 'Job')
    #1' (Admin) as a temporary placeholder 
    Job.objects.all().update(person_in_charge='1')


def convert_staging_location_values(apps, schema_editor):
    """Convert any text staging_location values to the new choice format"""
    Delivery = apps.get_model('clientapp', 'Delivery')
    
    # Map old values to new choice values
    value_mapping = {
        'Production': 'shelf-b',  # Map Production to Standard/Ready Today
        'Staging': 'shelf-a',     # Map Staging to Urgent/Priority  
        'Warehouse': 'warehouse',  # Keep warehouse as is
        'Ready': 'shelf-b',       # Map Ready to Standard/Ready Today
    }
    
    for delivery in Delivery.objects.all():
        old_value = delivery.staging_location
        if old_value in value_mapping:
            delivery.staging_location = value_mapping[old_value]
            delivery.save(update_fields=['staging_location'])


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0031_job_source_quote_channel_quote_checkout_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('carrier', models.CharField(blank=True, help_text='G4S, DHL, Sendy, etc.', max_length=100)),
                ('carrier_api_enabled', models.BooleanField(default=False, help_text='Use carrier API for real-time rates')),
                ('carrier_api_config', models.JSONField(blank=True, default=dict, help_text='API credentials/config')),
                ('pricing_type', models.CharField(choices=[('flat', 'Flat Rate'), ('weight_based', 'Weight Based'), ('price_based', 'Price Based'), ('api', 'API Calculated')], default='flat', max_length=20)),
                ('flat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_rate_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_rate_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('available_countries', models.JSONField(blank=True, default=list)),
                ('available_regions', models.JSONField(blank=True, default=list)),
                ('estimated_days_min', models.IntegerField(default=1)),
                ('estimated_days_max', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Shipping Methods',
                'ordering': ['is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tax_type', models.CharField(choices=[('vat', 'VAT'), ('gst', 'GST'), ('sales_tax', 'Sales Tax'), ('exempt', 'Tax Exempt')], default='vat', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate percentage', max_digits=5)),
                ('region_type', models.CharField(choices=[('country', 'Country'), ('state', 'State/Province'), ('city', 'City'), ('postal_code', 'Postal Code')], default='country', max_length=20)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('applies_to_b2b', models.BooleanField(default=True)),
                ('applies_to_b2c', models.BooleanField(default=True)),
                ('exempt_product_categories', models.JSONField(blank=True, default=list, help_text='List of category names')),
                ('exempt_business_types', models.JSONField(blank=True, default=list, help_text='List of business types')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tax Configurations',
                'ordering': ['country', 'state_province', 'city'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_number',
            field=models.CharField(default='DLV-TEMP', editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='package_photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='delivery',
            name='qc_inspection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='clientapp.qcinspection'),
        ),
        migrations.AlterField(
            model_name='client',
            name='delivery_instructions',
            field=models.TextField(blank=True, help_text='Specific delivery instructions (gate codes, contact person)'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='handoff_confirmed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='locked_evp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        
        # DATA CONVERSION BEFORE FIELD ALTERATIONS
        migrations.RunPython(convert_staging_location_values, migrations.RunPython.noop),
        migrations.RunPython(fix_person_in_charge_data, migrations.RunPython.noop),

        migrations.AlterField(
            model_name='delivery',
            name='staging_location',
            field=models.CharField(choices=[('shelf-a', 'Shelf A - Urgent/Priority'), ('shelf-b', 'Shelf B - Standard/Ready Today'), ('shelf-c', 'Shelf C - Future Delivery'), ('warehouse', 'Warehouse - Overflow')], default='shelf-b', max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('staged', 'Staged - Awaiting Pickup'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed')], default='staged', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='person_in_charge',
            field=models.ForeignKey(blank=True, help_text='Production Team member assigned to this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_category',
            field=models.CharField(blank=True, help_text='Print Products, Signage, Apparel', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_family',
            field=models.CharField(blank=True, help_text='Business Cards Family', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, help_text='Business Cards, Flyers, Brochures', max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariableoption',
            name='name',
            field=models.CharField(help_text='100pcs, 250gsm, Matte', max_length=100),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off'), ('free_shipping', 'Free Shipping'), ('buy_x_get_y', 'Buy X Get Y')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage or fixed amount', max_digits=10)),
                ('buy_quantity', models.IntegerField(blank=True, null=True)),
                ('get_quantity', models.IntegerField(blank=True, null=True)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('maximum_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('usage_limit', models.IntegerField(blank=True, help_text='Total times coupon can be used', null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('usage_limit_per_customer', models.IntegerField(default=1, help_text='Times per customer')),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_products', models.ManyToManyField(blank=True, help_text='Leave empty for all products', to='clientapp.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_guest', models.BooleanField(default=True, help_text='True if no account created')),
                ('is_active', models.BooleanField(default=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('preferred_currency', models.CharField(default='KES', max_length=3)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('matched_client', models.ForeignKey(blank=True, help_text='Auto-matched to existing Client if email/phone matches', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profiles', to='clientapp.client')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='For guest carts', max_length=40, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_abandoned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='clientapp.customer')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('billing', 'Billing Address'), ('shipping', 'Shipping Address'), ('both', 'Both')], default='both', max_length=10)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('is_default_billing', models.BooleanField(default=False)),
                ('is_default_shipping', models.BooleanField(default=False)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='clientapp.customer')),
            ],
            options={
                'verbose_name_plural': 'Customer Addresses',
                'ordering': ['-is_default_shipping', '-is_default_billing', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('template_file_url', models.URLField(blank=True, help_text='High-res template file')),
                ('preview_url', models.URLField(blank=True)),
                ('product_category', models.CharField(blank=True, max_length=100)),
                ('template_json', models.JSONField(default=dict, help_text='Template structure/configuration')),
                ('is_premium', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_templates', to='clientapp.product')),
            ],
            options={
                'ordering': ['-is_featured', '-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DesignState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='For guest designs', max_length=40, null=True)),
                ('design_json', models.JSONField(default=dict, help_text='Complete design state/configuration')),
                ('design_preview_url', models.URLField(blank=True)),
                ('is_from_template', models.BooleanField(default=False)),
                ('is_saved', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_states', to='clientapp.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.product')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientapp.designtemplate')),
            ],
            options={
                'ordering': ['-last_accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('in_production', 'In Production'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_transaction_id', models.CharField(blank=True, max_length=255)),
                ('payment_receipt_url', models.URLField(blank=True)),
                ('coupon_code', models.CharField(blank=True, max_length=50)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('billing_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_orders', to='clientapp.customeraddress')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientapp.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clientapp.customer')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storefront_orders', to='clientapp.job')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='clientapp.quote')),
                ('shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_orders', to='clientapp.customeraddress')),
                ('shipping_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientapp.shippingmethod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_sku', models.CharField(blank=True, max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('design_state_json', models.JSONField(blank=True, null=True)),
                ('design_file_url', models.URLField(blank=True)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clientapp.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientapp.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('stripe', 'Stripe'), ('pesapal', 'Pesapal'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash on Delivery')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('transaction_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Full gateway response')),
                ('receipt_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='clientapp.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='clientapp.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('title', models.CharField(max_length=200)),
                ('review_text', models.TextField()),
                ('review_photos', models.JSONField(blank=True, default=list, help_text='List of photo URLs')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clientapp.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='clientapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clientapp.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_sku', models.CharField(blank=True, max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('design_state_json', models.JSONField(blank=True, help_text='Stored design configuration', null=True)),
                ('design_file_url', models.URLField(blank=True, help_text='Link to uploaded design file')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clientapp.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.product')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('cart', 'product', 'design_state_json')},
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='clientapp_c_email_4679e2_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='clientapp_c_phone_d05514_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_guest'], name='clientapp_c_is_gues_4afd5d_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['customer', 'is_active'], name='clientapp_c_custome_2d1798_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key', 'is_active'], name='clientapp_c_session_f2c15a_idx'),
        ),
        migrations.AddIndex(
            model_name='designstate',
            index=models.Index(fields=['customer', 'is_saved'], name='clientapp_d_custome_338c28_idx'),
        ),
        migrations.AddIndex(
            model_name='designstate',
            index=models.Index(fields=['session_key', 'is_saved'], name='clientapp_d_session_36b1fa_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_id'], name='clientapp_p_transac_6d857f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['order', 'status'], name='clientapp_p_order_i_ea403d_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'is_approved'], name='clientapp_p_product_86f57f_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['rating'], name='clientapp_p_rating_8f3a4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'customer', 'order')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='clientapp_o_order_n_6b9f53_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='clientapp_o_custome_780c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='clientapp_o_payment_0ffe68_idx'),
        ),
    ]