# Generated by Django 5.2.7 on 2026-01-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0032_shippingmethod_taxconfiguration_and_more'),
    ]

    operations = [
    ]
