# Generated by Django 5.2.7 on 2026-01-09 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0033_convert_field_to_integer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('event_types', models.JSONField(default=list, help_text='List of event types to subscribe to')),
                ('secret_key', models.CharField(help_text='Secret key for signing payloads', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('max_retries', models.IntegerField(default=3)),
                ('retry_delay_seconds', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('discount', 'Discount'), ('surcharge', 'Surcharge'), ('correction', 'Correction')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='clientapp.order')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='clientapp.quote')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='For guest sessions', max_length=40, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_sessions', to='clientapp.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.product')),
            ],
            options={
                'ordering': ['-last_accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('design_file_url', models.URLField(help_text='Link to design file')),
                ('preview_url', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_format', models.CharField(blank=True, max_length=20)),
                ('design_json', models.JSONField(blank=True, default=dict, help_text='Design configuration/state')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked after approval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='clientapp.designsession')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('session', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='designsession',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_sessions', to='clientapp.designversion'),
        ),
        migrations.CreateModel(
            name='MaterialInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(help_text='e.g., 300gsm Matte Paper', max_length=200)),
                ('material_code', models.CharField(blank=True, max_length=100)),
                ('virtual_stock', models.DecimalField(decimal_places=2, default=0, help_text='Available stock (can be negative for backorders)', max_digits=12)),
                ('reserved_stock', models.DecimalField(decimal_places=2, default=0, help_text='Stock reserved by approved quotes/paid orders', max_digits=12)),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=0, help_text='Alert when stock falls below this', max_digits=12)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_variable_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='clientapp.productvariableoption')),
            ],
            options={
                'ordering': ['material_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('requires', 'Requires'), ('excludes', 'Excludes'), ('range', 'Range (Min/Max)'), ('conditional', 'Conditional'), ('turnaround_compatibility', 'Turnaround Compatibility')], max_length=30)),
                ('condition_json', models.JSONField(default=dict, help_text="Rule conditions (e.g., {'variable': 'paper', 'value': '300gsm', 'excludes': ['spot_uv']})")),
                ('message', models.CharField(help_text='Error message shown when rule is violated', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules checked first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='clientapp.product')),
            ],
            options={
                'ordering': ['-priority', 'rule_type'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('promotion_type', models.CharField(choices=[('bogo', 'Buy One Get One (BOGO)'), ('tiered', 'Tiered Discount (Spend X, Get Y Off)'), ('segment', 'Customer Segment Pricing'), ('loyalty', 'Loyalty Points Discount'), ('first_time', 'First-Time Customer Discount')], max_length=20)),
                ('buy_quantity', models.IntegerField(blank=True, null=True)),
                ('get_quantity', models.IntegerField(blank=True, null=True)),
                ('tier_rules', models.JSONField(blank=True, default=list, help_text="[{'min_spend': 10000, 'discount_amount': 1000}, ...]")),
                ('customer_segments', models.JSONField(blank=True, default=list, help_text='List of customer segment IDs or types')),
                ('segment_discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('usage_limit', models.IntegerField(blank=True, null=True)),
                ('usage_limit_per_customer', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligible_categories', models.ManyToManyField(blank=True, to='clientapp.productcategory')),
                ('eligible_products', models.ManyToManyField(blank=True, related_name='promotions', to='clientapp.product')),
                ('get_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bogo_promotions', to='clientapp.product')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ProofApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Required for rejections')),
                ('approved_by_email', models.EmailField(blank=True, help_text='Email of approver (customer)', max_length=254)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_approvals', to='clientapp.designversion')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proof_approvals', to='clientapp.order')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proof_approvals', to='clientapp.quote')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processed', 'Processed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('refund_transaction_id', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='clientapp.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='clientapp.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Remaining credit', max_digits=12)),
                ('reason', models.TextField()),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='clientapp.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='clientapp.order')),
                ('refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='clientapp.refund')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('tracking_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('carrier', models.CharField(blank=True, help_text='G4S, DHL, Sendy, etc.', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_updates', models.JSONField(blank=True, default=list, help_text='List of tracking status updates from carrier API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_items', models.ManyToManyField(related_name='shipments', to='clientapp.orderitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='clientapp.order')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientapp.customeraddress')),
                ('shipping_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientapp.shippingmethod')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientapp.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('entity_type', models.CharField(db_index=True, max_length=50)),
                ('entity_id', models.IntegerField(db_index=True)),
                ('event_type', models.CharField(choices=[('quote.created', 'Quote Created'), ('quote.sent', 'Quote Sent'), ('quote.approved', 'Quote Approved'), ('quote.rejected', 'Quote Rejected'), ('quote.expired', 'Quote Expired'), ('quote.cancelled', 'Quote Cancelled'), ('order.created', 'Order Created'), ('order.paid', 'Order Paid'), ('order.shipped', 'Order Shipped'), ('order.delivered', 'Order Delivered'), ('order.cancelled', 'Order Cancelled'), ('job.created', 'Job Created'), ('job.assigned', 'Job Assigned'), ('job.in_production', 'Job In Production'), ('job.completed', 'Job Completed'), ('payment.received', 'Payment Received'), ('payment.refunded', 'Payment Refunded'), ('vendor.assigned', 'Vendor Assigned'), ('vendor.failed', 'Vendor Failed'), ('sla.breached', 'SLA Breached'), ('sla.warning', 'SLA Warning'), ('custom', 'Custom Event')], db_index=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_number', models.IntegerField(default=1)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='clientapp.timelineevent')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='clientapp.webhooksubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='designsession',
            index=models.Index(fields=['customer', 'status'], name='clientapp_d_custome_58ef28_idx'),
        ),
        migrations.AddIndex(
            model_name='designsession',
            index=models.Index(fields=['session_key', 'status'], name='clientapp_d_session_e4221b_idx'),
        ),
        migrations.AddIndex(
            model_name='materialinventory',
            index=models.Index(fields=['material_name', 'is_active'], name='clientapp_m_materia_64edb6_idx'),
        ),
        migrations.AddIndex(
            model_name='productrule',
            index=models.Index(fields=['product', 'is_active'], name='clientapp_p_product_199681_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order', 'status'], name='clientapp_s_order_i_ba4406_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_id'], name='clientapp_s_trackin_dc1c72_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['entity_type', 'entity_id'], name='clientapp_t_entity__e15f97_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='clientapp_t_event_t_86b24d_idx'),
        ),
    ]
