# Generated by Django 5.2.7 on 2026-01-14 09:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0034_webhooksubscription_adjustment_designsession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quote',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Client LPO reference', max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='shipping_charges',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Delivery cost', max_digits=12),
        ),
        migrations.AlterField(
            model_name='turnaroundtime',
            name='name',
            field=models.CharField(help_text='Standard, 2-Day, Next-Day', max_length=100),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('product_type', models.CharField(help_text='e.g., Cap - Screen Print', max_length=255)),
                ('product_description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('required_by', models.DateField(help_text='Date vendor must deliver')),
                ('estimated_completion', models.DateField(blank=True, null=True)),
                ('actual_completion', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New - Awaiting Response'), ('awaiting_response', 'Awaiting Response'), ('needs_review', 'Needs Review - Awaiting Inspection'), ('quality_check', 'Quality Check - Pending Inspection'), ('in_production', 'In Production - On Track'), ('in_production_delayed', 'In Production - Delayed'), ('awaiting_approval', 'Awaiting Approval'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=50)),
                ('milestone', models.CharField(choices=[('awaiting_acceptance', 'Awaiting Acceptance'), ('in_production', 'In Production'), ('quality_check', 'Quality Check'), ('completed', 'Completed')], default='awaiting_acceptance', max_length=50)),
                ('vendor_accepted', models.BooleanField(default=False)),
                ('vendor_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('vendor_notes', models.TextField(blank=True)),
                ('assets_acknowledged', models.BooleanField(default=False)),
                ('assets_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('shipping_method', models.CharField(blank=True, choices=[('pickup', 'Print Duka Pickup'), ('vendor_ships', 'Vendor Ships')], max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('carrier', models.CharField(blank=True, max_length=50)),
                ('ready_for_pickup', models.BooleanField(default=False)),
                ('packaged_goods_photo', models.ImageField(blank=True, null=True, upload_to='po_packaging/')),
                ('coordination_group', models.CharField(blank=True, help_text='Group ID for multi-vendor coordination', max_length=50, null=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes not visible to vendor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_created', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='clientapp.job')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='clientapp.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialSubstitutionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_material', models.CharField(max_length=200)),
                ('original_pantone', models.CharField(blank=True, max_length=50)),
                ('original_supplier', models.CharField(blank=True, max_length=200)),
                ('proposed_material', models.CharField(max_length=200)),
                ('proposed_pantone', models.CharField(blank=True, max_length=50)),
                ('match_percentage', models.DecimalField(decimal_places=2, help_text='Estimated match percentage', max_digits=5)),
                ('comparison_photo', models.ImageField(upload_to='substitution_requests/')),
                ('justification', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending PT Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_requests', to='clientapp.purchaseorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('file_issue', 'File Issue'), ('material_shortage', 'Material Shortage'), ('equipment_failure', 'Equipment Failure'), ('spec_ambiguity', 'Spec Ambiguity'), ('material_substitution', 'Material Substitution Request'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='po_issues/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='clientapp.purchaseorder')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('question', 'Question'), ('update', 'Update'), ('issue', 'Issue'), ('confirmation', 'Confirmation')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='clientapp.purchaseorder')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_image', models.ImageField(upload_to='po_proofs/')),
                ('proof_type', models.CharField(choices=[('product_photo', 'Product Photo'), ('closeup_detail', 'Close-up Detail'), ('video', 'Video'), ('other', 'Other')], default='product_photo', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='clientapp.purchaseorder')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('vendor_invoice_ref', models.CharField(blank=True, help_text="Vendor's own invoice reference", max_length=100)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('line_items', models.JSONField(default=list, help_text='List of invoice line items')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Tax percentage', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_terms', models.CharField(blank=True, max_length=50)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted - Pending Review'), ('approved', 'Approved - Pending Payment'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('disputed', 'Disputed')], default='draft', max_length=20)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='vendor_invoices/%Y/%m/')),
                ('supporting_documents', models.JSONField(default=list, help_text='List of supporting document URLs')),
                ('vendor_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes not visible to vendor')),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_invoices', to='clientapp.job')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clientapp.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clientapp.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['vendor', 'status'], name='clientapp_p_vendor__7ac785_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['required_by'], name='clientapp_p_require_84104f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_number'], name='clientapp_p_po_numb_7d6851_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorinvoice',
            index=models.Index(fields=['vendor', 'status'], name='clientapp_v_vendor__66f1a8_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorinvoice',
            index=models.Index(fields=['invoice_date'], name='clientapp_v_invoice_fd2c10_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorinvoice',
            index=models.Index(fields=['invoice_number'], name='clientapp_v_invoice_82997a_idx'),
        ),
    ]
