# Generated by Django 5.2.7 on 2026-01-15 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0035_vendor_user_alter_quote_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productproduction',
            options={'verbose_name': 'Product Production Settings', 'verbose_name_plural': 'Product Production Settings'},
        ),
        migrations.AddField(
            model_name='product',
            name='allow_backorders',
            field=models.BooleanField(default=True, help_text='Allow orders when out of stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(default=10, help_text='Alert when stock falls below this'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Current stock quantity (for pre-made products)'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('made_to_order', 'Made to Order'), ('discontinued', 'Discontinued')], default='made_to_order', help_text='Current stock availability', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=False, help_text='Enable inventory tracking for this product'),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='accepts_transparency',
            field=models.BooleanField(default=False, help_text='Artwork can contain transparency'),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='bleed_mm',
            field=models.DecimalField(decimal_places=1, default=3.0, help_text='Bleed requirement in mm', max_digits=5),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='bom_ink_coverage_sqm',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Ink coverage per unit in sqm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='bom_primary_material',
            field=models.CharField(blank=True, help_text='e.g., 300gsm Art Card', max_length=200),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='bom_primary_quantity_per_unit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Material qty per product unit', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='bom_primary_size',
            field=models.CharField(blank=True, help_text='e.g., SRA3, A4, Custom', max_length=100),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='bom_primary_unit',
            field=models.CharField(blank=True, help_text='e.g., sheets, sqm, meters', max_length=20),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='bom_secondary_material',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='bom_secondary_quantity_per_unit',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='bom_secondary_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='bom_secondary_unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='color_profile',
            field=models.CharField(choices=[('cmyk', 'CMYK (Print Standard)'), ('rgb', 'RGB (Digital)'), ('pantone', 'Pantone Spot Colors'), ('cmyk_pantone', 'CMYK + Pantone')], default='cmyk', help_text='Required color mode for artwork', max_length=20),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='finish_binding',
            field=models.BooleanField(default=False, verbose_name='Binding'),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='finish_debossing',
            field=models.BooleanField(default=False, verbose_name='Debossing'),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='finish_die_cutting',
            field=models.BooleanField(default=False, verbose_name='Die Cutting'),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='finish_embossing',
            field=models.BooleanField(default=False, verbose_name='Embossing'),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='finish_foil_stamping',
            field=models.BooleanField(default=False, verbose_name='Foil Stamping'),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='finish_folding',
            field=models.BooleanField(default=False, verbose_name='Folding'),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='finish_lamination',
            field=models.BooleanField(default=False, verbose_name='Lamination'),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='finish_perforation',
            field=models.BooleanField(default=False, verbose_name='Perforation'),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='finish_scoring',
            field=models.BooleanField(default=False, verbose_name='Scoring'),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='finish_uv_coating',
            field=models.BooleanField(default=False, verbose_name='UV Coating'),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='max_ink_coverage',
            field=models.IntegerField(default=280, help_text='Maximum ink coverage percentage (usually 280-320%)'),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='min_resolution_dpi',
            field=models.IntegerField(default=300, help_text='Minimum required DPI for artwork'),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='qc_color_match',
            field=models.BooleanField(default=True, verbose_name='Color Match Check'),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='qc_cutting_accuracy',
            field=models.BooleanField(default=True, verbose_name='Cutting Accuracy Check'),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='qc_finish_quality',
            field=models.BooleanField(default=True, verbose_name='Finish Quality Check'),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='qc_registration',
            field=models.BooleanField(default=True, verbose_name='Registration Check'),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='requires_outlined_fonts',
            field=models.BooleanField(default=True, help_text='Fonts must be converted to outlines'),
        ),
        migrations.AddField(
            model_name='productproduction',
            name='safe_zone_mm',
            field=models.DecimalField(decimal_places=1, default=5.0, help_text='Safe zone from edge in mm', max_digits=5),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='machine_equipment',
            field=models.CharField(blank=True, help_text='e.g., HP Indigo 7900, Epson SureColor', max_length=100),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='production_method_detail',
            field=models.CharField(choices=[('digital_offset', 'Digital Offset Printing'), ('offset', 'Offset Printing'), ('screen', 'Screen Printing'), ('digital', 'Digital Printing'), ('large_format', 'Large Format Printing'), ('embroidery', 'Embroidery'), ('sublimation', 'Sublimation'), ('laser_engraving', 'Laser Engraving'), ('uv_printing', 'UV Printing'), ('other', 'Other')], default='digital_offset', max_length=100),
        ),
        migrations.AlterField(
            model_name='productproduction',
            name='production_notes',
            field=models.TextField(blank=True, help_text='Special production instructions'),
        ),
        migrations.CreateModel(
            name='ProductMaterialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_product', models.DecimalField(decimal_places=4, default=1.0, help_text='Amount of material consumed per product unit', max_digits=10)),
                ('material_type', models.CharField(choices=[('primary', 'Primary Material'), ('secondary', 'Secondary Material'), ('consumable', 'Consumable (Ink, etc.)'), ('packaging', 'Packaging')], default='primary', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='clientapp.materialinventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_links', to='clientapp.product')),
            ],
            options={
                'verbose_name': 'Product-Material Link',
                'verbose_name_plural': 'Product-Material Links',
                'ordering': ['product', 'material_type'],
                'unique_together': {('product', 'material')},
            },
        ),
    ]
