# Generated by Django 5.2.7 on 2026-01-16 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0036_gap_fixes_product_inventory_and_production'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorspecialty',
            name='vendors',
        ),
        migrations.AlterModelOptions(
            name='materialsubstitutionrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderissue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderproof',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='clientapp_p_vendor__7ac785_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='clientapp_p_require_84104f_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='clientapp_p_po_numb_7d6851_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendorinvoice',
            name='clientapp_v_vendor__66f1a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendorinvoice',
            name='clientapp_v_invoice_fd2c10_idx',
        ),
        migrations.RemoveIndex(
            model_name='vendorinvoice',
            name='clientapp_v_invoice_82997a_idx',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='special_instructions',
            new_name='blocked_reason',
        ),
        migrations.RemoveField(
            model_name='materialsubstitutionrequest',
            name='comparison_photo',
        ),
        migrations.RemoveField(
            model_name='materialsubstitutionrequest',
            name='original_pantone',
        ),
        migrations.RemoveField(
            model_name='materialsubstitutionrequest',
            name='original_supplier',
        ),
        migrations.RemoveField(
            model_name='materialsubstitutionrequest',
            name='proposed_pantone',
        ),
        migrations.RemoveField(
            model_name='materialsubstitutionrequest',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='materialsubstitutionrequest',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='materialsubstitutionrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='materialsubstitutionrequest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='actual_completion',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='coordination_group',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='estimated_completion',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='internal_notes',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='packaged_goods_photo',
        ),
        migrations.RemoveField(
            model_name='purchaseorderissue',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='purchaseorderissue',
            name='resolution_notes',
        ),
        migrations.RemoveField(
            model_name='purchaseorderissue',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorderissue',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorderissue',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorderproof',
            name='proof_type',
        ),
        migrations.RemoveField(
            model_name='purchaseorderproof',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='internal_notes_updated',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='internal_notes',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='supporting_documents',
        ),
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='vendor_notes',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='clientapp.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='completed_on_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='has_issues',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='invoice_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='invoice_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='last_activity_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='max_concurrent_jobs',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='performance_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='materialsubstitutionrequest',
            name='match_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='materialsubstitutionrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='product_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='required_by',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('NEW', 'New - Awaiting Acceptance'), ('ACCEPTED', 'Accepted'), ('IN_PRODUCTION', 'In Production'), ('AWAITING_APPROVAL', 'Awaiting Proof Approval'), ('BLOCKED', 'Blocked'), ('AT_RISK', 'At Risk'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorderissue',
            name='issue_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorderissue',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseordernote',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorderproof',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='lead_time',
            field=models.CharField(blank=True, help_text='e.g., 5 days', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='minimum_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='quality_rating',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='reliability_rating',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='services',
            field=models.TextField(blank=True, help_text='Comma-separated services', null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vps_score',
            field=models.CharField(blank=True, help_text='Grade e.g. A, B, C', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vps_score_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='line_items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_invoices', to='clientapp.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_invoices', to='clientapp.vendor'),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='vendor_invoice_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='VendorSpecialty',
        ),
    ]
