# Generated by Django 5.2.7 on 2026-01-21 08:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0039_alter_productvariable_name_quickbookstoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('in_production', 'In Production'), ('ready', 'Ready for Shipment'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shipping_address', models.TextField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_orders', to='clientapp.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_orders_created', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_portal_orders', to='clientapp.job')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_orders', to='clientapp.quote')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('overdue', 'Overdue'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('qb_invoice_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('is_synced_to_qb', models.BooleanField(default=False)),
                ('qb_last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('line_items_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_invoices', to='clientapp.client')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='clientapp.clientorder')),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='ClientOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_sku', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clientapp.clientorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('qb_payment_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('is_synced_to_qb', models.BooleanField(default=False)),
                ('reference_number', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_payments', to='clientapp.client')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='clientapp.clientinvoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientPortalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Account Owner'), ('admin', 'Portal Administrator'), ('user', 'Regular User'), ('viewer', 'View-Only Access')], default='user', max_length=20)),
                ('can_view_orders', models.BooleanField(default=True)),
                ('can_place_orders', models.BooleanField(default=True)),
                ('can_view_invoices', models.BooleanField(default=True)),
                ('can_view_payments', models.BooleanField(default=True)),
                ('can_submit_tickets', models.BooleanField(default=True)),
                ('can_access_documents', models.BooleanField(default=True)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_users', to='clientapp.client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_portal_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocumentLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(db_index=True, editable=False, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('doc_type', models.CharField(choices=[('invoice', 'Invoice'), ('quote', 'Quote'), ('specification', 'Specification'), ('artwork', 'Artwork'), ('proof', 'Proof'), ('manual', 'Manual'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=20)),
                ('file_url', models.URLField()),
                ('file_size', models.IntegerField(help_text='Size in bytes')),
                ('file_format', models.CharField(max_length=10)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_library', to='clientapp.client')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='clientapp.clientinvoice')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='clientapp.clientorder')),
                ('accessible_by', models.ManyToManyField(blank=True, related_name='accessible_documents', to='clientapp.clientportaluser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('order_submitted', 'Order Submitted'), ('invoice_viewed', 'Invoice Viewed'), ('invoice_downloaded', 'Invoice Downloaded'), ('payment_made', 'Payment Made'), ('ticket_created', 'Ticket Created'), ('document_downloaded', 'Document Downloaded'), ('login', 'Login'), ('profile_updated', 'Profile Updated')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientapp.clientinvoice')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientapp.clientorder')),
                ('portal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='clientapp.clientportaluser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientSupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('order', 'Order Issue'), ('invoice', 'Invoice/Billing'), ('delivery', 'Delivery'), ('quality', 'Quality'), ('technical', 'Technical'), ('other', 'Other')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('awaiting_client', 'Awaiting Client'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='clientapp.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='clientapp.clientinvoice')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='clientapp.clientorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientPortalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_confirmed', 'Order Confirmed'), ('order_status_update', 'Order Status Update'), ('invoice_issued', 'Invoice Issued'), ('payment_received', 'Payment Received'), ('delivery_scheduled', 'Delivery Scheduled'), ('ticket_reply', 'Support Ticket Reply'), ('announcement', 'Announcement'), ('reminder', 'Reminder')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='clientapp.clientinvoice')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='clientapp.clientorder')),
                ('portal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clientapp.clientportaluser')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='clientapp.clientsupportticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientTicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('attachment_url', models.URLField(blank=True)),
                ('is_internal', models.BooleanField(default=False, help_text='Internal note not visible to client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='clientapp.clientsupportticket')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_replies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='clientorder',
            index=models.Index(fields=['client', 'status'], name='clientapp_c_client__860010_idx'),
        ),
        migrations.AddIndex(
            model_name='clientorder',
            index=models.Index(fields=['order_number'], name='clientapp_c_order_n_30e285_idx'),
        ),
        migrations.AddIndex(
            model_name='clientinvoice',
            index=models.Index(fields=['client', 'status'], name='clientapp_c_client__b134f6_idx'),
        ),
        migrations.AddIndex(
            model_name='clientinvoice',
            index=models.Index(fields=['invoice_number'], name='clientapp_c_invoice_10b994_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpayment',
            index=models.Index(fields=['client', 'status'], name='clientapp_c_client__996517_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpayment',
            index=models.Index(fields=['payment_number'], name='clientapp_c_payment_e642b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientportaluser',
            unique_together={('user', 'client')},
        ),
        migrations.AddIndex(
            model_name='clientdocumentlibrary',
            index=models.Index(fields=['client', 'doc_type'], name='clientapp_c_client__0e0947_idx'),
        ),
        migrations.AddIndex(
            model_name='clientactivitylog',
            index=models.Index(fields=['portal_user', 'action_type'], name='clientapp_c_portal__b510aa_idx'),
        ),
        migrations.AddIndex(
            model_name='clientsupportticket',
            index=models.Index(fields=['client', 'status'], name='clientapp_c_client__7efb82_idx'),
        ),
        migrations.AddIndex(
            model_name='clientsupportticket',
            index=models.Index(fields=['ticket_number'], name='clientapp_c_ticket__7c5d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='clientportalnotification',
            index=models.Index(fields=['portal_user', 'is_read'], name='clientapp_c_portal__ae2de7_idx'),
        ),
    ]
