# Generated by Django 5.2.8 on 2026-01-21 11:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0040_clientorder_clientinvoice_clientorderitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pt_member', 'Production Team Member'), ('pt_manager', 'Production Team Manager'), ('director', 'Director'), ('ceo', 'CEO')], max_length=50, unique=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum invoice amount this role can approve', max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, default=0, help_text='Maximum invoice amount this role can approve (0 = unlimited)', max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['min_amount'],
            },
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='validation_errors',
            field=models.JSONField(blank=True, default=list, help_text='Validation errors from invoice validation service'),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='validation_warnings',
            field=models.JSONField(blank=True, default=list, help_text='Validation warnings'),
        ),
        migrations.CreateModel(
            name='InvoiceDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('vendor_responded', 'Vendor Responded'), ('pt_reviewing', 'PT Reviewing'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='clientapp.vendorinvoice')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_disputes', to='clientapp.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceDisputeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='dispute_attachments/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_responses', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='clientapp.invoicedispute')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job_vendor_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='clientapp.jobvendorstage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfitabilityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('job', 'Job'), ('vendor', 'Vendor'), ('product', 'Product'), ('process', 'Process')], max_length=20)),
                ('entity_id', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_end', '-margin_percentage'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='clientapp_p_entity__f247d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SLAEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('reminder', 'Reminder Email'), ('urgent', 'Urgent Notification'), ('manager', 'Manager Escalation'), ('director', 'Director Review')], max_length=20)),
                ('days_overdue', models.IntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_vendor_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='clientapp.jobvendorstage')),
                ('notified_users', models.ManyToManyField(related_name='sla_escalations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorPerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_jobs', models.IntegerField(default=0)),
                ('on_time_jobs', models.IntegerField(default=0)),
                ('on_time_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('qc_passed_jobs', models.IntegerField(default=0)),
                ('qc_failed_jobs', models.IntegerField(default=0)),
                ('qc_pass_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_response_time_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_invoice_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_invoice_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dispute_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='clientapp.vendor')),
            ],
            options={
                'verbose_name_plural': 'Vendor Performance Metrics',
            },
        ),
    ]
