# Generated by Django 5.2.7 on 2026-01-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0041_approvalthreshold_vendorinvoice_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
