# Generated by Django 5.2.7 on 2026-01-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0044_add_product_approval_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='email_clicked',
            field=models.BooleanField(default=False, help_text='Link clicked in email'),
        ),
        migrations.AddField(
            model_name='quote',
            name='email_clicked_at',
            field=models.DateTimeField(blank=True, help_text='When link was clicked', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='email_clicked_url',
            field=models.URLField(blank=True, help_text='Which link was clicked'),
        ),
        migrations.AddField(
            model_name='quote',
            name='email_delivered',
            field=models.BooleanField(default=False, help_text='Email delivered to recipient'),
        ),
        migrations.AddField(
            model_name='quote',
            name='email_delivered_at',
            field=models.DateTimeField(blank=True, help_text='When email was delivered', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='email_failed',
            field=models.BooleanField(default=False, help_text='Email delivery failed'),
        ),
        migrations.AddField(
            model_name='quote',
            name='email_failed_reason',
            field=models.TextField(blank=True, help_text='Reason for delivery failure'),
        ),
        migrations.AddField(
            model_name='quote',
            name='email_opened',
            field=models.BooleanField(default=False, help_text='Email opened by recipient'),
        ),
        migrations.AddField(
            model_name='quote',
            name='email_opened_at',
            field=models.DateTimeField(blank=True, help_text='When email was first opened', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='email_opened_by',
            field=models.EmailField(blank=True, help_text='Email address that opened the message', max_length=254),
        ),
        migrations.AddField(
            model_name='quote',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Email sent to client'),
        ),
        migrations.AddField(
            model_name='quote',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When email was sent', null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='mailgun_message_id',
            field=models.CharField(blank=True, help_text='Mailgun message ID for tracking', max_length=200),
        ),
    ]
