# Generated by Django 5.2.7 on 2026-01-29 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0045_quote_email_clicked_quote_email_clicked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assignment_notes',
            field=models.TextField(blank=True, help_text='Notes from AM when assigning job'),
        ),
        migrations.AddField(
            model_name='job',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='When was the last reminder sent', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='remind_days_before',
            field=models.IntegerField(default=2, help_text='Send reminder N days before deadline'),
        ),
        migrations.AddField(
            model_name='job',
            name='reminder_count',
            field=models.IntegerField(default=0, help_text='How many reminders have been sent'),
        ),
        migrations.CreateModel(
            name='JobMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('note', 'Note'), ('update', 'Update'), ('question', 'Question'), ('instruction', 'Instruction')], default='note', max_length=20)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='clientapp.job')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_messages_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_message', models.TextField(help_text='Message with reminder')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged')], default='sent', max_length=20)),
                ('days_until_deadline', models.IntegerField(help_text='How many days until deadline when reminder was sent')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='clientapp.job')),
                ('sent_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_reminders_sent', to=settings.AUTH_USER_MODEL)),
                ('sent_to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_reminders_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
