# Generated by Django 5.2.8 on 2026-01-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0046_job_assignment_notes_job_last_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('gsm', 'GSM (g/m²)'), ('kg', 'Kilograms'), ('g', 'Grams')], default='kg', max_length=5),
        ),
    ]
