# Generated by Django 5.2.8 on 2026-01-29 16:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0047_alter_product_weight_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('PT', 'Production Team'), ('Vendor', 'Vendor')], max_length=20)),
                ('sender_id', models.IntegerField()),
                ('sender_name', models.CharField(max_length=200)),
                ('recipient_type', models.CharField(choices=[('PT', 'Production Team'), ('Vendor', 'Vendor')], max_length=20)),
                ('recipient_id', models.IntegerField()),
                ('recipient_name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_task', models.BooleanField(default=False)),
                ('task_status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('task_priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=20)),
                ('task_due_date', models.DateTimeField(blank=True, null=True)),
                ('task_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase2_messages', to='clientapp.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='message_attachments/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='message_thumbnails/%Y/%m/%d/')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='clientapp.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_complete', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('on_schedule', 'On Schedule'), ('behind', 'Behind'), ('ahead', 'Ahead')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('issues', models.TextField(blank=True)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='clientapp.job')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='clientapp.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressUpdatePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='progress_photos/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('progress_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='clientapp.progressupdate')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProofSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_type', models.CharField(choices=[('sample', 'Sample'), ('final', 'Final'), ('before_after', 'Before/After')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('revision_requested', 'Revision Requested')], default='pending_review', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='clientapp.job')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_proofs', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='clientapp.vendor')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorPerformanceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quality_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('communication_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('jobs_completed_90_days', models.IntegerField(default=0)),
                ('on_time_jobs', models.IntegerField(default=0)),
                ('on_time_delivery_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_quality_rating', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_communication_rating', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_recalculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vps_history', to='clientapp.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Performance Score',
                'verbose_name_plural': 'Vendor Performance Scores',
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['job', 'created_at'], name='clientapp_m_job_id_f846f0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient_id', 'is_read'], name='clientapp_m_recipie_7fc378_idx'),
        ),
        migrations.AddIndex(
            model_name='progressupdate',
            index=models.Index(fields=['job', 'created_at'], name='clientapp_p_job_id_9ad716_idx'),
        ),
        migrations.AddIndex(
            model_name='progressupdate',
            index=models.Index(fields=['vendor', 'created_at'], name='clientapp_p_vendor__b25420_idx'),
        ),
        migrations.AddIndex(
            model_name='proofsubmission',
            index=models.Index(fields=['job', 'status'], name='clientapp_p_job_id_f8b40f_idx'),
        ),
        migrations.AddIndex(
            model_name='proofsubmission',
            index=models.Index(fields=['vendor', 'submitted_at'], name='clientapp_p_vendor__466dbc_idx'),
        ),
    ]
