# Generated by Django 5.2.7 on 2026-01-30 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0049_clientdashboard_paymentstatus_paymenthistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordernote',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='po_notes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='purchaseordernote',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_po_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InvoiceHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_reason', models.CharField(choices=[('qc_failed', 'QC Inspection Failed'), ('pending_approval', 'Pending PT Approval'), ('cost_discrepancy', 'Cost Discrepancy'), ('validation_error', 'Validation Error'), ('dispute', 'Payment Dispute'), ('other', 'Other')], max_length=30)),
                ('hold_details', models.TextField()),
                ('held_at', models.DateTimeField(auto_now_add=True)),
                ('released', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('held_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hold', to='clientapp.vendorinvoice')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_holds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-held_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialSubstitutionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_material', models.CharField(max_length=255)),
                ('substitute_material', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('original_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('substitute_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending PT Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('customer_notified', 'Customer Notified')], default='pending', max_length=20)),
                ('approval_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('customer_notified', models.BooleanField(default=False)),
                ('customer_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_substitutions', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='clientapp.purchaseorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['approval_status'], name='clientapp_m_approva_8bfebd_idx')],
            },
        ),
        migrations.CreateModel(
            name='POSMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('acceptance', 'Awaiting Acceptance'), ('production_start', 'Production Start'), ('production_mid', 'Production Midpoint'), ('quality_check', 'Quality Check'), ('final_approval', 'Final Approval'), ('delivery', 'Delivery')], max_length=30)),
                ('target_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_on_time', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('alert_sent', models.BooleanField(default=False)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='clientapp.purchaseorder')),
            ],
            options={
                'ordering': ['target_date'],
                'indexes': [models.Index(fields=['purchase_order', 'target_date'], name='clientapp_p_purchas_8297c2_idx'), models.Index(fields=['completed'], name='clientapp_p_complet_7b0046_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorCapacityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('capacity_warning', 'Capacity Warning (80%+)'), ('capacity_critical', 'Capacity Critical (100%+)'), ('overdue_job', 'Overdue Job'), ('sla_breach', 'SLA Breach'), ('deadline_approaching', 'Deadline Approaching (3 days)')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('message', models.TextField()),
                ('severity', models.IntegerField(default=1, help_text='1=info, 2=warning, 3=critical')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientapp.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_alerts', to='clientapp.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'status'], name='clientapp_v_vendor__d8931a_idx'), models.Index(fields=['alert_type'], name='clientapp_v_alert_t_060838_idx')],
            },
        ),
    ]
