# Generated by Django 5.2.8 on 2026-01-30 09:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0050_purchaseordernote_file_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('acknowledged', 'Acknowledged')], default='pending', max_length=20)),
                ('notification_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('portal', 'Portal Message')], default='email', max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeadlineCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_complexity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('vendor_capacity_available', models.IntegerField(default=5, help_text='Days available considering vendor capacity')),
                ('sla_days', models.IntegerField(default=14, help_text='Standard SLA for this product')),
                ('base_deadline', models.IntegerField(default=0, help_text='Base days required')),
                ('adjusted_deadline', models.IntegerField(default=0, help_text='Final deadline in days')),
                ('risk_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('calculation_notes', models.TextField(default='')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressUpdateBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('percentage_complete', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('behind_schedule', 'Behind Schedule')], default='on_track', max_length=50)),
                ('description', models.TextField(default='')),
                ('notes', models.TextField(blank=True)),
                ('next_milestone', models.CharField(blank=True, max_length=200)),
                ('next_milestone_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='QCProofLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('conditional', 'Conditional Pass')], default='passed', max_length=20)),
                ('qc_notes', models.TextField(blank=True)),
                ('auto_held_invoice', models.BooleanField(default=False)),
                ('hold_reason', models.CharField(blank=True, max_length=200)),
                ('vps_impact_calculated', models.BooleanField(default=False)),
                ('vps_score_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('linked_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-linked_at'],
            },
        ),
        migrations.CreateModel(
            name='VPSRecalculationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('qc_fail', 'QC Failure'), ('late_delivery', 'Late Delivery'), ('quality_issue', 'Quality Issue'), ('manual', 'Manual Recalculation')], max_length=50)),
                ('previous_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('new_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('score_change', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reason', models.TextField(default='')),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('recalculated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-recalculated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='slaescalation',
            options={'ordering': ['-escalated_at']},
        ),
        migrations.RemoveField(
            model_name='slaescalation',
            name='job_vendor_stage',
        ),
        migrations.RemoveField(
            model_name='slaescalation',
            name='level',
        ),
        migrations.RemoveField(
            model_name='slaescalation',
            name='message',
        ),
        migrations.RemoveField(
            model_name='slaescalation',
            name='notified_users',
        ),
        migrations.AddField(
            model_name='slaescalation',
            name='current_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slaescalation',
            name='escalated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='slaescalation',
            name='escalated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slaescalation',
            name='escalation_level',
            field=models.CharField(choices=[('level_1', 'Level 1 - Vendor Alert'), ('level_2', 'Level 2 - PT Review'), ('level_3', 'Level 3 - Management Escalation')], default='level_1', max_length=20),
        ),
        migrations.AddField(
            model_name='slaescalation',
            name='escalation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='slaescalation',
            name='escalation_reason',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='slaescalation',
            name='escalation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('resolved', 'Resolved'), ('overdue', 'Still Overdue')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='slaescalation',
            name='original_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slaescalation',
            name='pt_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slaescalation',
            name='pt_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slaescalation',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_escalations', to='clientapp.purchaseorder'),
        ),
        migrations.AddField(
            model_name='slaescalation',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='slaescalation',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slaescalation',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slaescalation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='slaescalation',
            name='vendor_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slaescalation',
            name='vendor_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slaescalation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='slaescalation',
            name='days_overdue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='slaescalation',
            index=models.Index(fields=['escalation_status'], name='clientapp_s_escalat_2a315e_idx'),
        ),
        migrations.AddIndex(
            model_name='slaescalation',
            index=models.Index(fields=['escalation_level'], name='clientapp_s_escalat_5faade_idx'),
        ),
        migrations.AddIndex(
            model_name='slaescalation',
            index=models.Index(fields=['purchase_order'], name='clientapp_s_purchas_19f5ee_idx'),
        ),
        migrations.AddField(
            model_name='customernotification',
            name='substitution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clientapp.materialsubstitutionapproval'),
        ),
        migrations.AddField(
            model_name='deadlinecalculation',
            name='purchase_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_calc', to='clientapp.purchaseorder'),
        ),
        migrations.AddField(
            model_name='progressupdatebatch',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_batches', to='clientapp.purchaseorder'),
        ),
        migrations.AddField(
            model_name='progressupdatebatch',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qcprooflink',
            name='proof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_links', to='clientapp.purchaseorderproof'),
        ),
        migrations.AddField(
            model_name='qcprooflink',
            name='qc_inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_links', to='clientapp.qcinspection'),
        ),
        migrations.AddField(
            model_name='vpsrecalculationlog',
            name='recalculated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vpsrecalculationlog',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vps_logs', to='clientapp.vendor'),
        ),
        migrations.AddIndex(
            model_name='progressupdatebatch',
            index=models.Index(fields=['purchase_order', '-submission_date'], name='clientapp_p_purchas_52e431_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='qcprooflink',
            unique_together={('qc_inspection', 'proof')},
        ),
        migrations.AddIndex(
            model_name='vpsrecalculationlog',
            index=models.Index(fields=['vendor', '-recalculated_at'], name='clientapp_v_vendor__0f4f37_idx'),
        ),
    ]
