# Generated by Django 5.2.8 on 2026-01-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0051_customernotification_deadlinecalculation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maintenance',
            field=models.TextField(blank=True, help_text='Product maintenance details and care instructions'),
        ),
    ]
