# Generated by Django 5.2.8 on 2026-01-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0052_add_maintenance_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpricing',
            name='lead_time_unit',
        ),
        migrations.RemoveField(
            model_name='productpricing',
            name='lead_time_value',
        ),
        migrations.RemoveField(
            model_name='productpricing',
            name='primary_vendor',
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('pieces', 'Pieces'), ('packs', 'Packs'), ('sets', 'Sets'), ('sqm', 'm²'), ('cm', 'Centimeters')], default='pieces', max_length=20),
        ),
    ]
